/**
 * GitHub Trending Tracker — Markdown 报告生成
 */

function generateReport(repos, analysis) {
  var today = formatDateCN();
  var issueNum = getIssueNumber_();
  var timeLabel = CONFIG.timeRange === 'daily' ? '日报' : (CONFIG.timeRange === 'weekly' ? '周报' : '月报');

  var lines = [];

  lines.push('# GitHub 热门项目' + timeLabel + ' — ' + today + '（第 ' + issueNum + ' 期）');
  lines.push('');
  lines.push('> 本报告由 GitHub Trending Tracker 自动生成');
  lines.push('');
  lines.push('---');
  lines.push('');

  // 本期亮点
  lines.push('## 本期亮点');
  lines.push('');
  var highlights = repos.slice(0, Math.min(3, repos.length));
  for (var h = 0; h < highlights.length; h++) {
    var hl = highlights[h];
    lines.push((h + 1) + '. **[' + hl.name + '](' + hl.url + ')**'
      + ' — ' + (hl.description || '暂无描述')
      + ' | ' + hl.periodLabel + ' +' + formatNumber(hl.periodStars) + ' stars');
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  // 项目详情
  lines.push('## 项目详情');
  lines.push('');

  for (var i = 0; i < repos.length; i++) {
    var repo = repos[i];
    lines.push('### ' + (i + 1) + '. [' + repo.name + '](' + repo.url + ')');
    lines.push('');

    lines.push('| 指标 | 数据 |');
    lines.push('|------|------|');
    lines.push('| Star | ' + formatNumber(repo.stars) + ' (+' + formatNumber(repo.periodStars) + ' ' + repo.periodLabel + ') |');
    lines.push('| Fork | ' + formatNumber(repo.forks) + ' |');
    lines.push('| 语言 | ' + (repo.language || 'N/A') + ' |');

    if (repo.fullData) {
      if (repo.fullData.license) {
        lines.push('| 协议 | ' + repo.fullData.license + ' |');
      }
      if (repo.fullData.topics && repo.fullData.topics.length > 0) {
        lines.push('| 标签 | ' + repo.fullData.topics.join(', ') + ' |');
      }
      if (repo.fullData.open_issues_count) {
        lines.push('| Open Issues | ' + repo.fullData.open_issues_count + ' |');
      }
    }

    lines.push('');

    if (repo.description) {
      lines.push('> ' + repo.description);
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // LLM 解读
  if (analysis && analysis.rawAnalysis) {
    lines.push('## AI 智能解读');
    lines.push('');
    lines.push(analysis.rawAnalysis);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by [GitHub Trending Tracker](https://github.com/' + CONFIG.githubRepo + ') on ' + formatDate() + '*');

  return lines.join('\n');
}

function getIssueNumber_() {
  var props = PropertiesService.getScriptProperties();
  var num = parseInt(props.getProperty('ISSUE_NUMBER') || '0', 10);
  num++;
  props.setProperty('ISSUE_NUMBER', String(num));
  return num;
}
